### ISSUE TITLE
Compatibility request

### ISSUE THREAD

**Issue by DamageMaximo** [mwoiii/simple-lunar-coins#1]
Hello, can you please make this mod compatible with the "Proper saves mod"?
It's a mod that allows the player to quit at any time and they will be able to continue a run another time, it adds a "Load" button to the character select screen to load the saved run, but once that is done the lunar coin amount gets defaulted to the starting amount because it thinks a new run has started, I ask you to make it compatible with that mod to make it know when to properly reset the lunar coin amount, please?

**Comment by mwoiii** [comment]
Implemented, update should be live shortly. Please let me know if you encounter any further issues 🙂
