### ISSUE TITLE
Visual effects bugged and amplified after recent updates

### ISSUE THREAD

**Issue by WesCook** [mwoiii/simple-lunar-coins#3]
With SimpleLunarCoins installed, visual effects are greatly amplified in the game.  They create blinding flashes, and often trigger large effects that make gameplay very difficult.  The effects seems a little random, as sometimes they would create large golden beams (that persisted), and other times would produce large rings (which faded away).  These often coincided with a flash bang to the screen, making everything temporarily white.

Many attacks would result in these distortions, including from other players and even enemies.  Two common triggers were Rex's secondary, and lemurian fireballs hitting walls.  It was very clear in regular gameplay however, and didn't require any specific setup.

The bug appears to be hardware-dependant.  It didn't happen on one testing PC, but did occur on another.  The graphics card drivers were fully updated.  The affected PC has these components:

```
GPU: Nvidia Geforce GTX 1050 Ti
CPU: Intel Core i7-4790
```

One important condition is that this bug only occurs in multiplayer as a client.  It does not occur as the host of a session, nor in singleplayer.  Someone else must host the game.

In testing previous versions, this behaviour appeared to be introduced in SimpleLunarCoins v1.2.2.  Earlier versions did not exhibit this behaviour.

These tests were run with just SimpleLunarCoins + dependencies installed.  The dependencies by themselves do not trigger this bug.

This data was collected across many runs of the game, system reboots, and after running Steam's game integrity verification.

Screenshots:
![Bug Example 1](https://github.com/user-attachments/assets/545ba31d-441e-4918-98b1-42876d7d81cc)
![Bug Example 2](https://github.com/user-attachments/assets/13844c30-f270-47bf-b037-c0d0449fc59a)

**Comment by mwoiii** [comment]
hey, thanks for reporting! versions before 1.2.2 shouldn't work properly with the latest patch of the game, which would likely explain why the issue doesn't occur, as certain parts of the mod will fail to load. with that in mind, I can narrow it down to a single method- but the only time it can create an effect is when a lunar coin is dropped while the "no coin droplets" setting is true, and you have it set to false if I'm not mistaken?

I'm led to believe there's another factor at play which I may not be qualified enough to offer guidance on, but just in case, [would you be able to attach the log file](https://h3vr-modding.github.io/wiki/installing/troubleshooting/log_file.html) from after a session in which the issue occurs? thanks 🙂

**Comment by WesCook** [comment]
Thanks for the swift response.  You're right that the setting "No Coin Droplets" was set to false.  However I've now tested it both ways, and the bug is present in both configurations.

Here is a copy of the output log.
[LogOutput.log](https://github.com/user-attachments/files/17008992/LogOutput.log)

The only line that jumps out to me is that it cannot load the field "InitialCoinChance" (which is set to 4).  This line doesn't occur on the stable PC.  I've included the configuration file as well.
[Miyowi.SimpleLunarCoins.cfg](https://github.com/user-attachments/files/17009021/Miyowi.SimpleLunarCoins.cfg.txt)

Note that the r2modman profile was copied via code, so all settings should match.

**Comment by mwoiii** [comment]
after investigating the log, it looks like MMHOOK_RoR2.dll isn't being found, which is core to the functionality of this mod as well as many others. I suspect that the visual glitches may therefore be a side effect of this error as these can impact the game in unpredictable ways, for example I recently had an issue with a mod I was working on in which due to an error, no items would be dropped from chests, even though the code itself wasn't affecting that aspect of the game in any way!

I've compared the log side-by-side with my own which works properly, and HookGenPatcher, the plugin which generates MMHOOK_RoR2.dll, seems to output the same messages to the console..

would you be able to verify that your plugins folder contains the MMHOOK folder, which itself contains MMHOOK_RoR2? for reference:
![ex1](https://github.com/user-attachments/assets/747d5cda-facd-4ec9-ad60-bff63f7744ac)
![ex2](https://github.com/user-attachments/assets/34b84e5d-07d8-4603-8555-0a15bbf875b8)

**Comment by WesCook** [comment]
Thanks for the information.  That sounds like a promising lead.  I'll check into that and get back to you.

Unfortunately as the weekend is over, it'll probably be a few days before I'm able to arrange for the multiplayer testing, but I'll do so as soon as is feasible.  Cheers.

**Comment by WesCook** [comment]
I was able to find a moment to test tonight.  Great suggestion - you were right!

The MMHOOK folder was not present on the affected PC.  After uninstalling the mod, then reinstalling directly, the folder and DLL were created after launching the game again.  And indeed this fixed the problem with chaotic visual effects.  As a plus, it also fixed some issues with other mods, such as PizzaClientLagFix freezing the game at 99% loading.

So, I wonder if this is because the profile was installed via code, and not directly.  Possibly it's not unpacking the necessary files to set up the dependencies.

I've noticed some others reporting the 99% loading bug with other mods in the RoR2 modding Discord too, and I wonder if this is a common problem that simply hasn't been recognized yet.  It might be something the core API devs need to look at.

Either way I'll close this now, both because it's resolved and because it's technically unrelated to SimpleLunarCoins.  Thanks very much for your help in debugging and tracking down the problem though.

**Comment by WesCook** [comment]
Just wanted to mention that the latest version of HookGenPatcher resolves this issue more permanently.  Apparently the configured filename would indeed be reset to default when importing via code, which led to all sorts of strange issues like the one above.

https://github.com/risk-of-thunder/Bepinex.Monomod.HookGenPatcher/commit/80e55e95c680dc2507047c67c5955c8b1147db89
